# Theme Configuration
logo: /assets/img/logo.png
show_downloads: false
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# Google Analytics
google_analytics: G-6XSVBQ6FSB

# Site Configuration
title: Wes Mason
description: IT Leader
